import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Caveat } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "../context/UserContext";
import { GlobalContextProvider } from "../context/GlobalContext";
import { RoomContextProvider } from "../context/RoomContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const cursiveFont = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Drawme Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${cursiveFont.variable} ${geistSans.variable} antialiased`}>
      <GlobalContextProvider>
        <UserContextProvider>
          <RoomContextProvider>
            <body
              className='font-[--font-geist-sans]'
            >
              {children}
            </body>
          </RoomContextProvider>
        </UserContextProvider>
      </GlobalContextProvider>
    </html>
  );
}
